const users = [
    {
        user_id: 1,
        user_name: "karlo",
        user_email: "karlo@gmail.com",
        user_password: "karlo"
    },    
    {
        user_id: 2,
        user_name: "ivan",
        user_email: "ivan@gmail.com",
        user_password: "ivan"
    },
    {
        user_id: 3,
        user_name: "martina",
        user_email: "martina@gmail.com",
        user_password: "martina"
    },    
    {
        user_id: 4,
        user_name: "jela",
        user_email: "jela@gmail.com",
        user_password: "jela"
    },
    {
        user_id: 5,
        user_name: "marko",
        user_email: "marko@gmail.com",
        user_password: "marko"
    },    
    {
        user_id: 6,
        user_name: "bule",
        user_email: "bule@gmail.com",
        user_password: "bule"
    },
    {
        user_id: 7,
        user_name: "kiki",
        user_email: "kiki@gmail.com",
        user_password: "kiki"
    },    
    {
        user_id: 8,
        user_name: "alex",
        user_email: "alex@gmail.com",
        user_password: "alex"
    },
    {
        user_id: 9,
        user_name: "taca",
        user_email: "taca@gmail.com",
        user_password: "taca"
    },    
    {
        user_id: 10,
        user_name: "joe",
        user_email: "joe@gmail.com",
        user_password: "joe"
    },
]

const matches = [ 
	{
        match_id: 1,
        match_name: "finished 1 5-a-side",
        date_start: "2020-01-02T12:30",
        date_end: "2020-01-02T23:59",
        venue: "the school pitch",
		users_signed_up: [1,2,3,4,5,6,7,8,9,10],
		users_attended: [1,2,3,4,5,6,7,8,9,10],
		home_score: "3",
		away_score: "2",
		home_scorers: [1,3,1],
		away_scorers: [9,8],
		home_team: [1,2,3,4,5],
		away_team: [6,7,8,9,10],
    },
	{
        match_id: 2,
        match_name: "current 1 5-a-side",
        date_start: "2020-01-03T12:30",
        date_end: "2020-01-03T23:59",
        venue: "the school pitch",
		users_signed_up: [1,2,3,4,5,6,7,8,9,10],
		users_attended: [1,2,3,4,5,6,7,8,9,10],
		home_score: "3",
		away_score: "2",
		home_scorers: [1,3,1],
		away_scorers: [9,8],
		home_team: [1,2,3,4,5],
		away_team: [6,7,8,9,10],
    },
	{
        match_id: 3,
        match_name: "upcoming 1 5-a-side",
        date_start: "2021-01-04T12:30",
        date_end: "2021-01-04T23:59",
        venue: "the school pitch",
		users_signed_up: [2,3,4,5,6,7,8,9,10],
		users_attended: [2,3,4,5,6,7,8,9,10],
		home_score: "3",
		away_score: "2",
		home_scorers: [1,3,1],
		away_scorers: [9,8],
		home_team: [1,2,3,4,5],
		away_team: [6,7,8,9,10],
    },
	{
        match_id: 4,
        match_name: "finished 2 5-a-side",
        date_start: "2020-01-02T11:30",
        date_end: "2020-01-02T23:59",
        venue: "the school pitch",
		users_signed_up: [1],
		users_attended: [1],
		home_score: "0",
		away_score: "0",
		home_scorers: [],
		away_scorers: [],
		home_team: [],
		away_team: [],
    },
	{
        match_id: 5,
        match_name: "current 2 5-a-side",
        date_start: "2020-01-03T11:30",
        date_end: "2020-01-03T23:59",
        venue: "the school pitch",
		users_signed_up: [2],
		users_attended: [2],
		home_score: "0",
		away_score: "0",
		home_scorers: [],
		away_scorers: [],
		home_team: [],
		away_team: [],
    },
	{
        match_id: 6,
        match_name: "upcoming 2 5-a-side",
        date_start: "2021-01-04T11:30",
        date_end: "2021-01-04T23:59",
        venue: "the school pitch",
		users_signed_up: [1],
		users_attended: [1],
		home_score: "0",
		away_score: "0",
		home_scorers: [],
		away_scorers: [],
		home_team: [],
		away_team: [],
    },


	{
        match_id: 7,
        match_name: "finished 3 5-a-side",
        date_start: "2020-01-02T10:30",
        date_end: "2020-01-02T23:59",
        venue: "the school pitch",
		users_signed_up: [1],
		users_attended: [1],
		home_score: "0",
		away_score: "0",
		home_scorers: [],
		away_scorers: [],
		home_team: [],
		away_team: [],
    },
	{
        match_id: 8,
        match_name: "current 3 5-a-side",
        date_start: "2020-01-03T10:30",
        date_end: "2020-01-03T23:59",
        venue: "the school pitch",
		users_signed_up: [1],
		users_attended: [1],
		home_score: "0",
		away_score: "0",
		home_scorers: [],
		away_scorers: [],
		home_team: [],
		away_team: [],
    },
	{
        match_id: 9,
        match_name: "upcoming 3 5-a-side",
        date_start: "2021-01-04T10:30",
        date_end: "2021-01-04T23:59",
        venue: "the school pitch",
		users_signed_up: [2],
		users_attended: [2],
		home_score: "0",
		away_score: "0",
		home_scorers: [],
		away_scorers: [],
		home_team: [],
		away_team: [],
    },
	{
        match_id: 10,
        match_name: "finished 4 5-a-side",
        date_start: "2020-01-02T09:30",
        date_end: "2020-01-02T23:59",
        venue: "the school pitch",
		users_signed_up: [1],
		users_attended: [1],
		home_score: "0",
		away_score: "0",
		home_scorers: [],
		away_scorers: [],
		home_team: [],
		away_team: [],
    },
	{
        match_id: 11,
        match_name: "current 4 5-a-side",
        date_start: "2020-01-03T09:30",
        date_end: "2020-01-03T23:59",
        venue: "the school pitch",
		users_signed_up: [1],
		users_attended: [1],
		home_score: "0",
		away_score: "0",
		home_scorers: [],
		away_scorers: [],
		home_team: [],
		away_team: [],
    },
	{
        match_id: 12,
        match_name: "upcoming 4 5-a-side",
        date_start: "2021-01-04T09:30",
        date_end: "2021-01-04T23:59",
        venue: "the school pitch",
		users_signed_up: [1],
		users_attended: [1],
		home_score: "0",
		away_score: "0",
		home_scorers: [],
		away_scorers: [],
		home_team: [],
		away_team: [],
    },
]

module.exports = {
    users, matches
}